package com.globalside.codingchallenge.rbac.db.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * JPA entity mapping to the {@code products} table. Kept separate from {@link
 * com.globalside.codingchallenge.rbac.db.model.ProductDto} so the persistence model can evolve
 * independently of the API contract.
 */
@Entity
@Table(name = "products")
@Getter
@Setter
public class ProductDbo {

    /** Primary key, generated by the database. */
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Integer id;

    /** Product name. */
    @Column(name = "name")
    String name;

    /** Free-text product description. */
    @Column(name = "description")
    String description;

    /** Price amount, denominated in {@link #currency}. */
    @Column(name = "price")
    Double price;

    /** ISO currency code for {@link #price} (e.g. {@code USD}). */
    @Column(name = "currency")
    String currency;

    /** Product category label. */
    @Column(name = "category")
    String category;

    /** Product brand name. */
    @Column(name = "brand")
    String brand;

    /** Product color. */
    @Column(name = "color")
    String color;

}
